### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Ninja"

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/minorseq#2]
hi,when I install minorseq ,I got this error~

thanks~
Si

**Comment by armintoepfer** [comment]
Do you have `ninja` installed?

**Comment by orangeSi** [comment]
no yet. When I run“cmake -GNinja -DCMAKE_INSTALL_PREFIX=~/bin .. “,I got that error

**Comment by armintoepfer** [comment]
There you, install https://ninja-build.org/
