### ISSUE TITLE
juliet - how to specify reference

### ISSUE THREAD

**Issue by colindaven** [PacificBiosciences/minorseq#4]
Hi,

I can use Juliet without a refererence without issues.

However I do not know how to specify a reference and really need to use one - human mitochondria.

Command example:
 /mnt/ngsnfs/tools/minorseq/build/juliet   --min-perc 10 --mode-phasing /lager2/rcug/seqres/HS/mito.fa ../91.combined.alignmentset.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unsupported input file: /lager2/rcug/seqres/HS/mito.fa of type ReferenceSet
Aborted (core dumped)

I could not see information on how to create or specifiy a reference on the command line, at present my reference looks like this:

>NC_012920.1 Homo sapiens mitochondrion, complete genome
GATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGG
GTATGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTC
CTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTA
ATTAATTAATGCTTGTAGGACATAATAATAACAATTGAATGTCTGCACAGCCACTTTCCACACAGACATC

Thanks
Colin

**Comment by armintoepfer** [comment]
Hi Colin,

you have to create a target config, described here: https://github.com/PacificBiosciences/minorseq/blob/develop/doc/JULIET.md#customized-target-configuration

It should also contain at least one gene that you are targeting. Let me know how it goes.

**Comment by colindaven** [comment]
Hi Armin, thanks.

Is there any GFF to JSON converter to do this at least approximately ? Or would you suggest writing a python script or similar ?

Thanks,
Colin

**Comment by armintoepfer** [comment]
No there is not. For our viral use cases, they still publish DRMs in PDFs :(

Be aware that the DRM section is optional. A minimal target config contains the reference name, reference sequence, and your gene of interest; similar to this:
```
{
    "genes": [
        {
            "name": "ABL1",
            "begin": 193,
            "end": 3585
        }
    ],
    "referenceName": "NM_005157.5",
    "referenceSequence": "TTAACAGGCGCGTCCC..."
}
```
This will already allow you to call variants wrt a reference. DRMs are only for annotation.

**Comment by colindaven** [comment]
Thanks, that's useful information. I am not interested in DRMs.  I will look into getting time to write a script for this. 

One last question. Am I right in thinking that, when not being supplied with a reference, the tool inspects the BAM file as a kind of multiple sequence alignment ? We had some trouble inspecting positions (which is why I am looking into the reference sequence option).

Thanks by the way for the nice documentation.

**Comment by armintoepfer** [comment]
Without a reference, juliet doesn't have any clue about individual ORFs and assumes that the whole reference is one ORF. Our initial use case without a target config is small amplicons aligned against individual genes that represent one ORF.

You are one step further and need to provide the ORFs of the human mitochondria. If you succeed, please let me know and maybe post your script for the others. If you don't succeed, also let me know!

 - Armin
