### ISSUE TITLE
Problems about ninja

### ISSUE THREAD

**Issue by ttbond** [PacificBiosciences/minorseq#5]
Hi~
When I tried to install minorseq, I got trapped at the command of "cmake -GNinja -DCMAKE_INSTALL_PREFIX=~/bin .. && ninja". The error message is "The detected version of Ninja () is less than the version of Ninja required by CMake (1.3)." But I have installed Ninja with version of (1.8.2). Could you help me how to solve it or show me the command with make not ninja. Thx very much.

**Comment by armintoepfer** [comment]
Hi!

Then don't use ninja ¯\_(ツ)_/¯
`cmake .. -DCMAKE_INSTALL_PREFIX=~/bin .. && make`

Or use the official tarball from https://www.pacb.com/support/software-downloads/
